name: Code Quality Checks

on:
  push:
    branches: ["**"]
    tags: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        #with:
          #python-version: 3.10

      - name: Test environment
        run: pip install -e .["test"]

      - name: Test with isort
        run: isort --check-only --diff .

      - name: Test with refurb
        run: refurb . --quiet
